[als.webcam]
video = 0
thresholds = { 0 = "night", 9 = "dark", 16 = "dim", 25 = "low", 35 = "moderate", 45 = "normal", 60 = "bright", 75 = "outdoors" }

[[output.backlight]]
name = "eDP-1"
path = "/sys/class/backlight/intel_backlight"
capturer = "wlroots"
