[als.webcam]
video = 0
thresholds = { 0 = "night", 10 = "dark", 25 = "dim", 40 = "normal", 55 = "bright", 70 = "outdoors" }

[[output.backlight]]
name = "eDP-1"
path = "/sys/class/backlight/intel_backlight"
capturer = "wlroots"
